# Generated by Django 4.0.6 on 2022-07-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
        ('store', '0004_auto_20210610_1442'),
    ]

    operations = [
    ]
